bashfeed: detect unescaped HTML attributes
* scripts/bashfeed: Report when there is unescaped meta-data,
which would result in an invalid XML feed.

Reported-by: Jan Willamowius <jan@willamowius.de>

diff --git a/scripts/bashfeed b/scripts/bashfeed
--- a/scripts/bashfeed
+++ b/scripts/bashfeed
@@ -9,7 +9,7 @@
 #   1.1     - Jun 26 2006 - Exclude files with "Exclude from bashfeed"
 #                           HTML comment within the first 10 lines.
 #   1.2     - May 01 2007 - Add author elements (from html if present)
-#   1.3     - Jan 12 2011
+#   1.4     - May 04 2011
 #    http://github.com/pixelb/scripts/commits/master/scripts/bashfeed
 
 # Just run this script from the root directory of your web site and
@@ -85,6 +85,8 @@ echo "
 <language>`echo $LANG | sed 's/\(..\)_.*/\1/'`</language>
 "
 
+xml_unescaped() { sed 's/&amp;//g; s/&[lg]t;//g; s/&quot;//g' | grep -q "[&<>]"; }
+
 find $1 -type f -printf "%p\t%T@\n" |
 sed 's/^\.\///' | # strip leading ./ when "$1" is empty
 sort -k2,2nr |
@@ -107,6 +109,11 @@ while read file; do
         keywords=`sed -n 's/.*<META.*NAME="keywords".*CONTENT="\(.*\)".*/\1/ip;T;q' < "$file"`
         description=`sed -n 's/.*<META.*NAME="description".*CONTENT="\(.*\)".*/\1/ip;T;q' < "$file"`
         page_author=`sed -n 's/.*<META.*NAME="author".*CONTENT="\(.*\)".*/\1/ip;T;q' < "$file"`
+        extracted_text="$title $keywords $description$ $page_author"
+        if echo "$extracted_text" | xml_unescaped; then
+          echo "Error: HTML metadata in $file will not produce a valid XML feed" >&2
+          exit 1
+        fi
     elif [ -x "$file" ]; then # I always have a 1 line description on line 3 of my scripts
         description=`sed -n '3s/# \(.*\)/\1/p' "$file"`
     fi
@@ -134,6 +141,6 @@ echo "
     $page_author$tags<description><![CDATA[$description<!--$force_update-->]]></description>
 </item>
 "
-done
+done &&
 echo '</channel>
 </rss>'
