timeout: support dash and pdksh
Rewritten to use lower level primitives than job control.
This supports dash, ksh and pdksh at least.
Note there also is a pric/timeouttest.sh script provided.

diff --git a/scripts/timeout b/scripts/timeout
--- a/scripts/timeout
+++ b/scripts/timeout
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/bin/sh
 
 # Execute a command with a timeout
 
@@ -22,6 +22,9 @@
 #                       it doesn't actually timeout. So enforce bash for now.
 #                       Also change exit on timeout from 128 to 124
 #                       to match coreutils.
+#    V2.0, Oct 30 2009, Ján Sáreník <jasan@x31.com>
+#                       Rewritten to cover compatibility with other
+#                       Bourne shell implementations (pdksh, dash)
 
 if [ "$#" -lt "2" ]; then
     echo "Usage:   `basename $0` timeout_in_seconds command" >&2
@@ -31,12 +34,23 @@ fi
 
 cleanup()
 {
-    kill %1 2>/dev/null             #kill sleep $timeout if running
-    kill %2 2>/dev/null && exit 124 #kill monitored job if running
+    trap - ALRM               #reset handler to default
+    kill -ALRM $a 2>/dev/null #stop timer subshell if running
+    kill $! 2>/dev/null &&    #kill last job
+      exit 124                #exit with 124 if it was running
 }
 
-set -m               #enable job control
-trap "cleanup" CHLD  #cleanup after timeout or command
-timeout=$1 && shift  #first param is timeout in seconds
-sleep $timeout&      #start the timeout
-"$@"                 #start the job
+watchit()
+{
+    trap "cleanup" ALRM
+    sleep $1& wait
+    kill -ALRM $$
+}
+
+watchit $1& a=$!         #start the timeout
+shift                    #first param was timeout for sleep
+trap "cleanup" ALRM INT  #cleanup after timeout
+"$@"& wait $!; RET=$?    #start the job wait for it and save its return value
+kill -ALRM $a            #send ALRM signal to watchit
+wait $a                  #wait for watchit to finish cleanup
+exit $RET                #return the value
